---
- name: test playbook
  hosts: docker
  tasks:

  - name: install git
    apt:
      name: git
      state: latest

  - name: add cwp dir
    file:
      path: /cwp
      state: directory
      mode: 0750

  - name: git clone cwp repo
    git:
      repo: https://github.com/RobertBarrow/cwp.git
      dest: /cwp
      version: HEAD
      force: yes
  
  - name: rename example CSV file
    copy:
      src: /cwp/python/CWP_example.CSV
      dest: /cwp/python/CWP.CSV
      remote_src: yes
      
  - name: change python script file ownership, group and mode.
    file:
      path: /cwp/python/sb.py
      owner: root
      group: root
      mode: 0700

  - name: install pip
    apt:
      name: python-pip
      state: latest

  - name: run python script
    command: python sb.py
    args:
      chdir: /cwp/python/
      creates: /cwp/python/CWP_ANALYSIS.CSV

  - name: download CWP_ANALYSIS.CSV 
    fetch:
      src: /cwp/python/CWP_ANALYSIS.CSV
      dest: CWP_ANALYSIS.CSV
